#set text(font: ("pingfang sc","Microsoft Sans Serif"),lang: "zh")
#lorem(300)
#set page(columns: 2,
  width: auto,
  height: auto,
  numbering: "1/1",
  )
#text(font:"Songti SC", fill: red, size: 44pt)[fhsdfjfjsdjhj]

#strong[djflksakldjflkasjkdl]

*dklfsjlk*

#strike[dkfksjdhfjksadjfsjd]

#underline()[kdfjkshdfjkhsjkdfhjkashdjkf]

#underline(stroke: 1pt, evade: false, offset: 2pt)[#text(fill: red,font:"Songti SC")[你好我是你的]]

= jxhbi
== odjfk
=== jkdjfks 

1. dkfksjdhfjksadjfsjd
2. jdfhjdska
3. jdfhjdska
  1. jfjdsfkjdlas
  2. jfjdsfkjdlas
    1. kjdshfkjhd

hjkhjk
+ djflksakldjflkasjkdl
+ jdsjfk
6. fjklsdj


sdkjhfjk

- djflksakldjflkasjkdl
- jhjdj
  - djflksakldjflkasjkdl
    - sdfkjahjkjkf
      - jhjdj

#align(center)[*kjdfjksdfjk*]
#align(right)[*kjdfjksdfjk*]



